# Generated by Django 4.1 on 2022-09-02 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_age',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='display_birthday',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='display_education',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='display_email',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='display_followed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='display_following',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='display_friends',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='display_gender',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='display_joined',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='display_location',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='display_phone',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='display_work',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_joined',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
