# Generated by Django 4.1 on 2022-09-03 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capapp', '0004_remove_comments_name_remove_comments_text_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='stext_content',
            new_name='text_content',
        ),
    ]
