# Generated by Django 4.1 on 2022-09-03 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capapp', '0006_images_user_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='display_joined',
            new_name='display_date_joined',
        ),
    ]
