# Generated by Django 4.1 on 2022-09-03 03:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capapp', '0007_rename_display_joined_profile_display_date_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='display_followed',
            new_name='display_followers',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='followed',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='lat',
            field=models.CharField(default=0, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='long',
            field=models.CharField(default=0, max_length=9),
            preserve_default=False,
        ),
    ]
