# Generated by Django 4.1 on 2022-09-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capapp', '0008_rename_display_followed_profile_display_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lat',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='long',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
