# Generated by Django 4.1 on 2022-09-07 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capapp', '0009_profile_location_alter_profile_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_birthday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_date_joined',
            field=models.BooleanField(default=False),
        ),
    ]
