# Generated by Django 4.1 on 2022-09-07 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capapp', '0010_alter_profile_display_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_age',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_education',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_followers',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_following',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_friends',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_gender',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_location',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_phone',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_work',
            field=models.BooleanField(default=False),
        ),
    ]
