# Generated by Django 4.1 on 2022-09-09 01:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capapp', '0011_alter_profile_display_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends_unconfirmed',
            field=models.ManyToManyField(blank=True, related_name='friends_unconfirmed_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
