# Generated by Django 4.1 on 2022-09-09 01:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capapp', '0012_profile_friends_unconfirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends_unconfirmed',
        ),
        migrations.AddField(
            model_name='profile',
            name='unconfirmed',
            field=models.ManyToManyField(blank=True, related_name='unconfirmed_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
