# Generated by Django 4.1 on 2022-09-09 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capapp', '0013_remove_profile_friends_unconfirmed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profile_image',
        ),
    ]
