# Generated by Django 4.1 on 2022-09-13 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capapp', '0015_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='subments',
        ),
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.AddField(
            model_name='comments',
            name='parentment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subments', to='capapp.comments'),
        ),
        migrations.AddField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='capapp.post'),
            preserve_default=False,
        ),
    ]
