# Generated by Django 4.1 on 2022-09-20 01:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capapp', '0017_alter_post_private_alter_post_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blocked',
            field=models.ManyToManyField(blank=True, related_name='blocked_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
