# Generated by Django 4.1 on 2022-09-27 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capapp', '0020_chat_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='user',
            new_name='users',
        ),
    ]
