# Generated by Django 4.1 on 2022-09-28 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capapp', '0022_alter_message_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text_content',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
